base_url: /hub-guide
title: FOSSLight Hub Guide
lang: ko
description: FOSSLight Hub Korean Guide

remote_theme: fosslight/guide_theme

top_link: "https://fosslight.github.io/hub-guide-en"
top_link_word: "English"

addons_title: "FOSSLight Homepage"
addons_url: "https://fosslight.org/ko"

google:
  gtag: G-7EHWGTQYDY
  
readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
